create table if not exists "addresses" (
    id            bigint generated by default as identity
    constraint addresses_pkey
    primary key,

    country        varchar(255)     not null,
    city           varchar(255),
    street         varchar(255),
    house          varchar(255),
    apartment      varchar(255),
    date_start     timestamp        not null,
    user_id        bigint,
    CONSTRAINT fk_user_id
    FOREIGN KEY (user_id) REFERENCES users (id)
    );